name: Meu Primeiro Workflow de CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  meu-primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Exibe RA e Nome
        run: echo "RA: 6324505 - Nome: Kau찾 Augusto"
      - name: Mostra o diret처rio de trabalho
        run: pwd
      - name: Mostra o nome do reposit처rio
        run: echo "Nome do reposit처rio: ${{ github.repository }}"
